name: CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # allows manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.6'
      
      - name: Install sample_sklearn
        run: pip install git+https//${{secrets.ACCESS_TOKEN}}@github.com/sarodz/sample_sklearn@main

      - name: Install dependencies
        run: make install

      # - name: Test
      #   run: make test
